name: Plan (NonProd)
on:
  pull_request:
    branches:
      - master
    paths:
      - "terraform/**"
env:
  TF_IN_AUTOMATION: "true"
  TERRAFORM_VERSION: 0.14.7
  AWS_REGION: us-east-1
  TF_VAR_cbpro_key: ${{ secrets.CBPRO_BUY_KEY }}
  TF_VAR_cbpro_passphrase: ${{ secrets.CBPRO_BUY_PASSPHRASE }}
  TF_VAR_cbpro_secret: ${{ secrets.CBPRO_BUY_SECRET }}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: [self-hosted, tsa]
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: actions/checkout@v2
      - name: Terraform init
        run: |
          terraform init -input=false \
            -backend-config=region=${{ env.region }} \
            -backend-config=access_key=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -backend-config=secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -backend-config=bucket=${{ secrets.STATE_BUCKET }} \
            -backend-config=key=${{ secrets.STATE_KEY }}
      - name: Terraform plan
        run: |
          terraform plan -no-color -input=false -out=tfplan
